version: '3.8'

services:
  app:
    build: .
    container_name: our-portfolio-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:5174:5173"  # Биндим на localhost для безопасности
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=production  # Для продакшена
    command: npm run dev -- --host 0.0.0.0